import { ReactNode } from "react";
import "./global.css"
import ReduxProvider from "./components/ReduxProvider";
import { AuthProvider } from "./components/Provider";
import Navbar from "./components/Navbar";
import SessionWrapper from "@/utils/Wrapper";
import ProtectedPage from "./ProtectedPage";
import Notification from "./components/Notification";
import { Inter } from "next/font/google";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <AuthProvider>
            <ReduxProvider>
              <SessionWrapper />
              <Notification />
              <Navbar />
              <ProtectedPage>{children}</ProtectedPage>
            </ReduxProvider>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}